name: Test Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ] 
  schedule:
    # Runs "at midnight every weekday except weekends"
    - cron: '0 0 * * 1-5'

jobs:
  test-job:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Execute tests
        run: mvn test --file pom.xml
